edenai/edenai-apis

- edenai_apis/apis/amazon/amazon_api.py
- edenai_apis/apis/amazon/config.py
- edenai_apis/apis/amazon/helpers.py
- edenai_apis/apis/ibm/config.py
- edenai_apis/apis/ibm/ibm_api.py
- edenai_apis/utils/upload_s3.py
For ibm and amazon config.py --> change clients dict to functions
> [reface] testable providers without keys

- edenai_apis/apis/microsoft/microsoft_helpers.py
Just fixing attribute errors on Microsoft Financial Parser
> [fix] microsoft financial_parser AttributeError

- edenai_apis/apis/openai/openai_text_api.py
Fix ValidationError CustomNER OpenAI
> [fix] ValidationError CustomNER OpenAI

- edenai_apis/apis/picpurify/picpurify_api.py
> Fix JsonDecodeError when picpurify server returns an 5XX error (not a json response)

- edenai_apis/apis/originalityai/outputs/text/ai_detection_output.json
- edenai_apis/apis/sapling/outputs/text/ai_detection_output.json
- edenai_apis/apis/winstonai/outputs/text/ai_detection_output.json
- edenai_apis/features/text/ai_detection/ai_detection_dataclass.py
- edenai_apis/features/text/ai_detection/ai_detection_response.json
I added the ai_socre_detail field in the AI Detection dataclass so it will replace ai_score when in became deprecated!
> [feat] add ai_score_detail for ai_detection dataclass

- edenai_apis/api_keys/ai21labs_settings_template.json
- edenai_apis/apis/ai21labs/ai21labs_api.py
- edenai_apis/apis/ai21labs/info.json
- edenai_apis/apis/ai21labs/outputs/text/summarize_output.json
- edenai_apis/apis/anthropic/anthropic_api.py
- edenai_apis/apis/anthropic/info.json
- edenai_apis/apis/anthropic/outputs/text/summarize_output.json
Added summarization feature for Anthropic and AI21labs providers
Anthropic:
- Keep using bedrock with LLM prompt for text generation
AI21labs:
- Switch to AI21labs' API endpoint exclusively for summarization
- Continuing to use bedrock for text generation
Future plan: Transition from bedrock to AI21labs API for text generation
> Eaiscrum 926 add anthropic 21 labs as providers of summarization say in the prompt summarize in the original language

- edenai_apis/apis/ai21labs/ai21labs_api.py
- edenai_apis/apis/ai21labs/info.json
- edenai_apis/apis/ai21labs/outputs/text/spell_check_output.json
add the provider ai21labs for the spell check subfeature
> [feat] add AI21labs spell check

- edenai_apis/apis/openai/info.json
remove openai text generation deprecated models
> remvove deprecated models.

- edenai_apis/apis/astria/outputs/image/generation_fine_tuning_generate_image_async_output.json
- edenai_apis/features/image/generation_fine_tuning/generate_image_async/generation_fine_tuning_generate_image_async_args.py
Make astria tests pass : 
- Adding config files astria_settings.
- Template response output
- return project id in get args
> [fix] make astria tests pass

- edenai_apis/apis/voxist/voxist_api.py
- Remove voxist code as it's a depcreated provider.
> deprecate voxist

- edenai_apis/apis/sentisight/sentisight_api.py
- edenai_apis/tests/features/test_image_search.py
- Fix Nyckel image search test (upload/delete)
- Change sentisight output for upload & delete phase (return standardized response dataclass)
> fix image search tests

- edenai_apis/apis/api4ai/api4ai_api.py
- edenai_apis/apis/api4ai/info.json
- edenai_apis/apis/api4ai/outputs/image/logo_detection_output.json
- edenai_apis/apis/clarifai/clarifai_api.py
- edenai_apis/apis/clarifai/info.json
- edenai_apis/apis/google/google_image_api.py
- edenai_apis/apis/google/info.json
- edenai_apis/apis/jina/info.json
- edenai_apis/apis/microsoft/info.json
- edenai_apis/apis/microsoft/microsoft_image_api.py
- edenai_apis/apis/smartclick/info.json
- edenai_apis/apis/smartclick/smartclick_api.py
- edenai_apis/features/image/image_interface.py
- edenai_apis/features/image/logo_detection/logo_detection_args.py
- Make logo detection take models
- Add v2 & v1 for api4ai as model providers
> EAISCRUM-1009-update-api-4-ai-image-logo-detection

- edenai_apis/apis/anthropic/anthropic_api.py
- edenai_apis/apis/anthropic/info.json
- edenai_apis/apis/anthropic/outputs/text/chat_output.json
- edenai_apis/apis/anthropic/outputs/text/summarize_output.json
- Add chat endpoint for anthropic (stream/completion)
- Add claude v3 
- Change summarize from completion to chat with claude 3 as default
> add anthropic chat & claude 3

- edenai_apis/apis/affinda/models.py
- edenai_apis/apis/affinda/outputs/ocr/invoice_parser_output.json
> EAISCRUM-1105-validation-error-affinda-invoice-financial-parser

- edenai_apis/apis/perplexityai/perplexityai_api.py
[issue](https://edenai-py.sentry.io/issues/5076110696/?project=6420758&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=15d&stream_index=18)
> [fix] perplexityai chat stream key error

- edenai_apis/apis/openai/openai_text_api.py
[issue](https://edenai-py.sentry.io/issues/5065471329/?project=6420758&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=15d&stream_index=12)
> [fix] openai code generation chuncked encoding error

- edenai_apis/apis/microsoft/microsoft_helpers.py
At the same time fix KeyErrors, AttributeErrors, TypeErrors, IndexErrors
when accessing microsoft response object
> [refactor] microsoft invoice_parsing's parsing

- edenai_apis/apis/nyckel/nyckel_api.py
[issue](https://edenai-py.sentry.io/issues/5089294233/?project=6420758&query=is%3Aunresolved+%21title%3AProvider%2A&referrer=issue-stream&statsPeriod=24h&stream_index=24)
> [fix] nyckel automl classification train KeyError

- edenai_apis/apis/openai/helpers.py
- edenai_apis/apis/openai/openai_text_api.py
- edenai_apis/apis/openai/prompts_guidelines.py
- edenai_apis/features/text/text_interface.py
- new providers for prompt optimization (target providers)
- for mistral & meta there is not a lot of prompt engineering documentation so we use for the moment the same guidelines as openai
> new providers for prompt optimization

- edenai_apis/apis/microsoft/microsoft_text_api.py
[issue](https://edenai-py.sentry.io/issues/4700738163/?project=6420758&query=is%3Aunresolved+%21title%3AProvider%2A&referrer=issue-stream&statsPeriod=24h&stream_index=18)
> [fix] microsoft summarize TypeError

- edenai_apis/apis/affinda/affinda_api.py
- edenai_apis/apis/affinda/outputs/ocr/resume_parser_output.json
- edenai_apis/apis/affinda/standardization.py
- edenai_apis/apis/extracta/outputs/ocr/resume_parser_output.json
- edenai_apis/apis/hireability/outputs/ocr/resume_parser_output.json
- edenai_apis/apis/klippa/outputs/ocr/resume_parser_output.json
- edenai_apis/apis/senseloaf/outputs/ocr/resume_parser_output.json
- edenai_apis/features/ocr/resume_parser/resume_parser_dataclass.py
- edenai_apis/features/ocr/resume_parser/resume_parser_response.json
New standardization [here](https://draftable.sharepoint.com/:x:/g/Ef1bE0UIn5RAg0Rlt8QQV3cBnspnT90AFTJfS8SYAwaxEg?rtime=GTtEohtz3Eg)
> [Feat] use nextgen resume parser for resume parser

- edenai_apis/apis/google/google_text_api.py
- edenai_apis/apis/google/outputs/text/chat_output.json
- edenai_apis/apis/google/outputs/text/generation_output.json
add google's gemini models to edenai apis in text generation  and text chat
> Gemini v1.5 pro

- edenai_apis/api_keys/google_settings_template.json
- edenai_apis/apis/google/google_helpers.py
- edenai_apis/apis/google/google_image_api.py
- edenai_apis/apis/google/google_multimodal_api.py
- edenai_apis/apis/google/google_text_api.py
- Using directly rest api for genai for geminis models
> [feat] change chat & text generation to gen ai

- edenai_apis/apis/google/outputs/audio/speech_to_text_async_output.json
- requirements.in
- requirements.txt
Google-cloud-speech 2.14.1 suddenly didn't accept language_codes> Updated version works
> Update google-cloud-speech version

- edenai_apis/apis/google/google_image_api.py
- edenai_apis/apis/google/outputs/image/question_answer_output.json
- edenai_apis/features/image/question_answer/question_answer_args.py
Remove old deprecated models/code of google question_answer (gemini-vision/imagen) and replace them with gemini pro/flash
> [Fix] remove deprecated models of google

- edenai_apis/apis/openai/helpers.py
- edenai_apis/apis/openai/openai_api.py
- edenai_apis/apis/openai/openai_image_api.py
for the moment only include the function for image generation
> moderate input openai image generation

- edenai_apis/apis/google/google_video_api.py
[Jira issue](https://edenai-py.sentry.io/issues/6046064136/?project=6420758&query=is%3Aunresolved%20%21title%3AProvider%2A&referrer=issue-stream&sort=date&statsPeriod=1d&stream_index=11)
> [fix] google video person tracking KeyError on landmark_tracking

- edenai_apis/apis/amazon/errors.py
- edenai_apis/apis/anthropic/outputs/text/chat_output.json
- edenai_apis/apis/cohere/outputs/text/chat_output.json
- edenai_apis/apis/google/google_video_api.py
- edenai_apis/apis/google/outputs/text/chat_output.json
- edenai_apis/apis/meta/outputs/text/chat_output.json
- edenai_apis/apis/mistral/outputs/text/chat_output.json
- edenai_apis/apis/openai/info.json
- edenai_apis/apis/openai/openai_image_api.py
- edenai_apis/apis/openai/outputs/text/chat_output.json
- edenai_apis/apis/perplexityai/outputs/text/chat_output.json
- edenai_apis/apis/replicate/outputs/text/chat_output.json
- edenai_apis/apis/sightengine/info.json
- edenai_apis/apis/sightengine/sightengine_api.py
- edenai_apis/apis/stabilityai/stabilityai_api.py
- edenai_apis/features/image/image_interface.py
- edenai_apis/features/image/variation/variation_args.py
- edenai_apis/features/text/chat/chat_args.py
- edenai_apis/features/text/chat/chat_response.json
- edenai_apis/features/video/video_interface.py
- edenai_apis/tests/features/test_async_features.py
- edenai_apis/tests/features/test_sync_features.py
- edenai_apis/tests/test_providers_errors.py
- Video q&a asyn job deprecated test_async_subfeature[providers13-video-question_answer_async]
- Perplexityai deprecated model
- Chat tests with tool_results
- Sightengine load feature tests : [test_load_info_subfeature_provider[sightengine-image-deepfake_detection-,
- Test_load_info_subfeature_provider[sightengine-video-deepfake_detection_async-]]
- Image Variation
- Input text too long
- Invalid file audio duration
- Skip api calls for GitHub action cicd
> SD2-948-fix-all-edenai-apis-failing-tests

- edenai_apis/llmengine/clients/__init__.py
- edenai_apis/llmengine/clients/llm_models/model_management_interface.py
- edenai_apis/llmengine/tests/conftest.py
- edenai_apis/llmengine/tests/test_model_management_interface.py
- **Model registry interface**
- **Update the model register interface**
> Interface for registering LiteLLM models without having to import litellm directly
